contact_links:
  - name: Racket Discourse - A forum for all things related to Racket. Ask your questions here!
    url: https://racket.discourse.group
    about: Please ask and answer questions here.
  - name: Racket Slack - A chat list for all things related to Racket. Ask your questions here!
    url: https://racket-slack.herokuapp.com/
    about: Click here to join.
    
